//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text;
using System.Threading.Tasks;

namespace IHCHelixAzureProject.IHCClient
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsResultASO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class wsResultASO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IHCHelixAzureProject.IHCClient.ArrayOfSpOCCASOExportReportByFilter_Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IHCHelixAzureProject.IHCClient.ArrayOfSpOCCASOExportReportByFilter_Result result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                if ((object.ReferenceEquals(this.resultField, value) != true))
                {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.errorField, value) != true))
                {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSpOCCASOExportReportByFilter_Result", Namespace="http://tempuri.org/", ItemName="spOCCASOExportReportByFilter_Result")]
    [System.SerializableAttribute()]
    public class ArrayOfSpOCCASOExportReportByFilter_Result : System.Collections.Generic.List<IHCHelixAzureProject.IHCClient.spOCCASOExportReportByFilter_Result>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spOCCASOExportReportByFilter_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class spOCCASOExportReportByFilter_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime dtStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeighbourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BloodTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASOTypeField;
        
        private System.Nullable<System.DateTime> dtLastASOField;
        
        private System.Nullable<System.DateTime> dtLastValidThruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASOStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseField;
        
        private bool OffshoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostCenterField;
        
        private bool CheckupField;
        
        private int idCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        private System.Nullable<bool> AlteredField;
        
        private System.Nullable<double> IMCField;
        
        private System.Nullable<double> WeightField;
        
        private System.Nullable<double> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorCRMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorCRMUFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASOResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EyeColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicalRecordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Patient
        {
            get
            {
                return this.PatientField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PatientField, value) != true))
                {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CompanyField, value) != true))
                {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true))
                {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                if ((this.BirthDateField.Equals(value) != true))
                {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true))
                {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true))
                {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CPF
        {
            get
            {
                return this.CPFField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CPFField, value) != true))
                {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PIS
        {
            get
            {
                return this.PISField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PISField, value) != true))
                {
                    this.PISField = value;
                    this.RaisePropertyChanged("PIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StatusField, value) != true))
                {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime dtStatus
        {
            get
            {
                return this.dtStatusField;
            }
            set
            {
                if ((this.dtStatusField.Equals(value) != true))
                {
                    this.dtStatusField = value;
                    this.RaisePropertyChanged("dtStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PositionField, value) != true))
                {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AddressField, value) != true))
                {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Neighbour
        {
            get
            {
                return this.NeighbourField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NeighbourField, value) != true))
                {
                    this.NeighbourField = value;
                    this.RaisePropertyChanged("Neighbour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityField, value) != true))
                {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string UF
        {
            get
            {
                return this.UFField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UFField, value) != true))
                {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PhoneField, value) != true))
                {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Cellphone
        {
            get
            {
                return this.CellphoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CellphoneField, value) != true))
                {
                    this.CellphoneField = value;
                    this.RaisePropertyChanged("Cellphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GenderField, value) != true))
                {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string BloodType
        {
            get
            {
                return this.BloodTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BloodTypeField, value) != true))
                {
                    this.BloodTypeField = value;
                    this.RaisePropertyChanged("BloodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string ASOType
        {
            get
            {
                return this.ASOTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ASOTypeField, value) != true))
                {
                    this.ASOTypeField = value;
                    this.RaisePropertyChanged("ASOType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<System.DateTime> dtLastASO
        {
            get
            {
                return this.dtLastASOField;
            }
            set
            {
                if ((this.dtLastASOField.Equals(value) != true))
                {
                    this.dtLastASOField = value;
                    this.RaisePropertyChanged("dtLastASO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public System.Nullable<System.DateTime> dtLastValidThru
        {
            get
            {
                return this.dtLastValidThruField;
            }
            set
            {
                if ((this.dtLastValidThruField.Equals(value) != true))
                {
                    this.dtLastValidThruField = value;
                    this.RaisePropertyChanged("dtLastValidThru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocationField, value) != true))
                {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ASOStatus
        {
            get
            {
                return this.ASOStatusField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ASOStatusField, value) != true))
                {
                    this.ASOStatusField = value;
                    this.RaisePropertyChanged("ASOStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Base
        {
            get
            {
                return this.BaseField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BaseField, value) != true))
                {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public bool Offshore
        {
            get
            {
                return this.OffshoreField;
            }
            set
            {
                if ((this.OffshoreField.Equals(value) != true))
                {
                    this.OffshoreField = value;
                    this.RaisePropertyChanged("Offshore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string BusinessUnit
        {
            get
            {
                return this.BusinessUnitField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BusinessUnitField, value) != true))
                {
                    this.BusinessUnitField = value;
                    this.RaisePropertyChanged("BusinessUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string CostCenter
        {
            get
            {
                return this.CostCenterField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CostCenterField, value) != true))
                {
                    this.CostCenterField = value;
                    this.RaisePropertyChanged("CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public bool Checkup
        {
            get
            {
                return this.CheckupField;
            }
            set
            {
                if ((this.CheckupField.Equals(value) != true))
                {
                    this.CheckupField = value;
                    this.RaisePropertyChanged("Checkup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public int idCompany
        {
            get
            {
                return this.idCompanyField;
            }
            set
            {
                if ((this.idCompanyField.Equals(value) != true))
                {
                    this.idCompanyField = value;
                    this.RaisePropertyChanged("idCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ResultField, value) != true))
                {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public System.Nullable<bool> Altered
        {
            get
            {
                return this.AlteredField;
            }
            set
            {
                if ((this.AlteredField.Equals(value) != true))
                {
                    this.AlteredField = value;
                    this.RaisePropertyChanged("Altered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public System.Nullable<double> IMC
        {
            get
            {
                return this.IMCField;
            }
            set
            {
                if ((this.IMCField.Equals(value) != true))
                {
                    this.IMCField = value;
                    this.RaisePropertyChanged("IMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public System.Nullable<double> Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                if ((this.WeightField.Equals(value) != true))
                {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public System.Nullable<double> Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                if ((this.HeightField.Equals(value) != true))
                {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string DoctorName
        {
            get
            {
                return this.DoctorNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DoctorNameField, value) != true))
                {
                    this.DoctorNameField = value;
                    this.RaisePropertyChanged("DoctorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string DoctorCRM
        {
            get
            {
                return this.DoctorCRMField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DoctorCRMField, value) != true))
                {
                    this.DoctorCRMField = value;
                    this.RaisePropertyChanged("DoctorCRM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string DoctorCRMUF
        {
            get
            {
                return this.DoctorCRMUFField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DoctorCRMUFField, value) != true))
                {
                    this.DoctorCRMUFField = value;
                    this.RaisePropertyChanged("DoctorCRMUF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string InternalID
        {
            get
            {
                return this.InternalIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InternalIDField, value) != true))
                {
                    this.InternalIDField = value;
                    this.RaisePropertyChanged("InternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string Exam
        {
            get
            {
                return this.ExamField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExamField, value) != true))
                {
                    this.ExamField = value;
                    this.RaisePropertyChanged("Exam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string ASOResult
        {
            get
            {
                return this.ASOResultField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ASOResultField, value) != true))
                {
                    this.ASOResultField = value;
                    this.RaisePropertyChanged("ASOResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NationalityField, value) != true))
                {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string EyeColor
        {
            get
            {
                return this.EyeColorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EyeColorField, value) != true))
                {
                    this.EyeColorField = value;
                    this.RaisePropertyChanged("EyeColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string BP
        {
            get
            {
                return this.BPField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BPField, value) != true))
                {
                    this.BPField = value;
                    this.RaisePropertyChanged("BP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string ClinicalRecords
        {
            get
            {
                return this.ClinicalRecordsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClinicalRecordsField, value) != true))
                {
                    this.ClinicalRecordsField = value;
                    this.RaisePropertyChanged("ClinicalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsResultASOHelix", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class wsResultASOHelix : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IHCHelixAzureProject.IHCClient.ArrayOfSpWSHelixASOs_Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IHCHelixAzureProject.IHCClient.ArrayOfSpWSHelixASOs_Result result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                if ((object.ReferenceEquals(this.resultField, value) != true))
                {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.errorField, value) != true))
                {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSpWSHelixASOs_Result", Namespace="http://tempuri.org/", ItemName="spWSHelixASOs_Result")]
    [System.SerializableAttribute()]
    public class ArrayOfSpWSHelixASOs_Result : System.Collections.Generic.List<IHCHelixAzureProject.IHCClient.spWSHelixASOs_Result>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spWSHelixASOs_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class spWSHelixASOs_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrabalhadorField;
        
        private int TipoField;
        
        private System.Nullable<System.DateTime> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsavelField;
        
        private int AptoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdField, value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Trabalhador
        {
            get
            {
                return this.TrabalhadorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TrabalhadorField, value) != true))
                {
                    this.TrabalhadorField = value;
                    this.RaisePropertyChanged("Trabalhador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                if ((this.TipoField.Equals(value) != true))
                {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                if ((this.DataField.Equals(value) != true))
                {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Local
        {
            get
            {
                return this.LocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocalField, value) != true))
                {
                    this.LocalField = value;
                    this.RaisePropertyChanged("Local");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Responsavel
        {
            get
            {
                return this.ResponsavelField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ResponsavelField, value) != true))
                {
                    this.ResponsavelField = value;
                    this.RaisePropertyChanged("Responsavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Apto
        {
            get
            {
                return this.AptoField;
            }
            set
            {
                if ((this.AptoField.Equals(value) != true))
                {
                    this.AptoField = value;
                    this.RaisePropertyChanged("Apto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHCHelixAzureProject.IHCClient.AsosSoap")]
    public interface AsosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetASOs", ReplyAction="*")]
        IHCHelixAzureProject.IHCClient.GetASOsResponse GetASOs(IHCHelixAzureProject.IHCClient.GetASOsRequest request);
        System.Threading.Tasks.Task<wsResultASO> GetASOsAsync(System.DateTime dtStart, System.DateTime dtEnd, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetASOs", ReplyAction="*")]
        System.IAsyncResult BeginGetASOs(IHCHelixAzureProject.IHCClient.GetASOsRequest request, System.AsyncCallback callback, object asyncState);
        
        IHCHelixAzureProject.IHCClient.GetASOsResponse EndGetASOs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExams", ReplyAction="*")]
        IHCHelixAzureProject.IHCClient.GetExamsResponse GetExams(IHCHelixAzureProject.IHCClient.GetExamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetExams", ReplyAction="*")]
        System.IAsyncResult BeginGetExams(IHCHelixAzureProject.IHCClient.GetExamsRequest request, System.AsyncCallback callback, object asyncState);
        
        IHCHelixAzureProject.IHCClient.GetExamsResponse EndGetExams(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetASOHelix", ReplyAction="*")]
        IHCHelixAzureProject.IHCClient.GetASOHelixResponse GetASOHelix(IHCHelixAzureProject.IHCClient.GetASOHelixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetASOHelix", ReplyAction="*")]
        System.IAsyncResult BeginGetASOHelix(IHCHelixAzureProject.IHCClient.GetASOHelixRequest request, System.AsyncCallback callback, object asyncState);
        
        IHCHelixAzureProject.IHCClient.GetASOHelixResponse EndGetASOHelix(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetASOsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetASOs", Namespace="http://tempuri.org/", Order=0)]
        public IHCHelixAzureProject.IHCClient.GetASOsRequestBody Body;
        
        public GetASOsRequest()
        {
        }
        
        public GetASOsRequest(IHCHelixAzureProject.IHCClient.GetASOsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetASOsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime dtEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authKey;
        
        public GetASOsRequestBody()
        {
        }
        
        public GetASOsRequestBody(System.DateTime dtStart, System.DateTime dtEnd, string authKey)
        {
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
            this.authKey = authKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetASOsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetASOsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IHCHelixAzureProject.IHCClient.GetASOsResponseBody Body;
        
        public GetASOsResponse()
        {
        }
        
        public GetASOsResponse(IHCHelixAzureProject.IHCClient.GetASOsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetASOsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IHCHelixAzureProject.IHCClient.wsResultASO GetASOsResult;
        
        public GetASOsResponseBody()
        {
        }
        
        public GetASOsResponseBody(IHCHelixAzureProject.IHCClient.wsResultASO GetASOsResult)
        {
            this.GetASOsResult = GetASOsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExamsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExams", Namespace="http://tempuri.org/", Order=0)]
        public IHCHelixAzureProject.IHCClient.GetExamsRequestBody Body;
        
        public GetExamsRequest()
        {
        }
        
        public GetExamsRequest(IHCHelixAzureProject.IHCClient.GetExamsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExamsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime dtEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authKey;
        
        public GetExamsRequestBody()
        {
        }
        
        public GetExamsRequestBody(System.DateTime dtStart, System.DateTime dtEnd, string authKey)
        {
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
            this.authKey = authKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExamsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExamsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IHCHelixAzureProject.IHCClient.GetExamsResponseBody Body;
        
        public GetExamsResponse()
        {
        }
        
        public GetExamsResponse(IHCHelixAzureProject.IHCClient.GetExamsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExamsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IHCHelixAzureProject.IHCClient.wsResultASO GetExamsResult;
        
        public GetExamsResponseBody()
        {
        }
        
        public GetExamsResponseBody(IHCHelixAzureProject.IHCClient.wsResultASO GetExamsResult)
        {
            this.GetExamsResult = GetExamsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetASOHelixRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetASOHelix", Namespace="http://tempuri.org/", Order=0)]
        public IHCHelixAzureProject.IHCClient.GetASOHelixRequestBody Body;
        
        public GetASOHelixRequest()
        {
        }
        
        public GetASOHelixRequest(IHCHelixAzureProject.IHCClient.GetASOHelixRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetASOHelixRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime dtEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authKey;
        
        public GetASOHelixRequestBody()
        {
        }
        
        public GetASOHelixRequestBody(System.DateTime dtStart, System.DateTime dtEnd, string authKey)
        {
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
            this.authKey = authKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetASOHelixResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetASOHelixResponse", Namespace="http://tempuri.org/", Order=0)]
        public IHCHelixAzureProject.IHCClient.GetASOHelixResponseBody Body;
        
        public GetASOHelixResponse()
        {
        }
        
        public GetASOHelixResponse(IHCHelixAzureProject.IHCClient.GetASOHelixResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetASOHelixResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IHCHelixAzureProject.IHCClient.wsResultASOHelix GetASOHelixResult;
        
        public GetASOHelixResponseBody()
        {
        }
        
        public GetASOHelixResponseBody(IHCHelixAzureProject.IHCClient.wsResultASOHelix GetASOHelixResult)
        {
            this.GetASOHelixResult = GetASOHelixResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsosSoapChannel : IHCHelixAzureProject.IHCClient.AsosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsosSoapClient : System.ServiceModel.ClientBase<IHCHelixAzureProject.IHCClient.AsosSoap>, IHCHelixAzureProject.IHCClient.AsosSoap
    {
        
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);        
        
        public AsosSoapClient()
        {
        }
        
        public AsosSoapClient(EndpointConfiguration endpointConfiguration) :
            base(AsosSoapClient.GetBindingForEndpoint(endpointConfiguration), AsosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }        
 
        
        public AsosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public IHCHelixAzureProject.IHCClient.GetASOsResponse GetASOs(IHCHelixAzureProject.IHCClient.GetASOsRequest request)
        {
            return base.Channel.GetASOs(request);
        }
        
        public System.IAsyncResult BeginGetASOs(IHCHelixAzureProject.IHCClient.GetASOsRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetASOs(request, callback, asyncState);
        }
        
        public IHCHelixAzureProject.IHCClient.GetASOsResponse EndGetASOs(System.IAsyncResult result)
        {
            return base.Channel.EndGetASOs(result);
        }
        
        public IHCHelixAzureProject.IHCClient.GetExamsResponse GetExams(IHCHelixAzureProject.IHCClient.GetExamsRequest request)
        {
            return base.Channel.GetExams(request);
        }
        
        public System.IAsyncResult BeginGetExams(IHCHelixAzureProject.IHCClient.GetExamsRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetExams(request, callback, asyncState);
        }
        
        public IHCHelixAzureProject.IHCClient.GetExamsResponse EndGetExams(System.IAsyncResult result)
        {
            return base.Channel.EndGetExams(result);
        }
        
        public IHCHelixAzureProject.IHCClient.GetASOHelixResponse GetASOHelix(IHCHelixAzureProject.IHCClient.GetASOHelixRequest request)
        {
            return base.Channel.GetASOHelix(request);
        }
        
        public System.IAsyncResult BeginGetASOHelix(IHCHelixAzureProject.IHCClient.GetASOHelixRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetASOHelix(request, callback, asyncState);
        }
        
        public IHCHelixAzureProject.IHCClient.GetASOHelixResponse EndGetASOHelix(System.IAsyncResult result)
        {
            return base.Channel.EndGetASOHelix(result);
        }

        public System.Threading.Tasks.Task<wsResultASO>GetASOsAsync(DateTime dtStart, DateTime dtEnd, string authKey)
        {
            return base.Channel.GetASOsAsync(dtStart, dtEnd, authKey);
        }

        public Task<wsResultASO> GetExamsAsync(DateTime dtStart, DateTime dtEnd, string authKey)
        {
            throw new NotImplementedException();
        }

        public Task<wsResultASOHelix> GetASOHelixAsync(DateTime dtStart, DateTime dtEnd, string authKey)
        {
            throw new NotImplementedException();
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AsosSoap))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpsSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AsosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }     
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AsosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://brazil.medstatus.app/ws/asos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AsosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://brazil.medstatus.app/ws/asos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }        
        
        public enum EndpointConfiguration
        {

            AsosSoap,

            AsosSoap12,
        }        
    }
}
